### ISSUE TITLE
Validation error for recipes

### ISSUE THREAD

**Issue by lionelasshauer** [ephes/kptncook#32]
Hi everyone,

after installing version 0.0.17 (according to pipx), I am able to get the required token and could also pull my favorites.
But it will instantly throw the following error for one recipe. I tried to pick specific recipes via oid, but they all return the same thing. The download into the json file did work regardless of the error.

ValidationError: 1 validation error for Recipe
steps.1.image
  Field required [type=missing, input_value={'title': {'en': 'Quarter...ari',
'pt': 'melão'}}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

Whenever I try to list the local recipes or run the Paprika export I get the same error.
Is there any way to fix this?

Python 3.10.13 macOS

**Comment by ephes** [comment]
Thanks for your report.

Is this maybe fixed with 0.0.18 or 0.0.19?

**Comment by lionelasshauer** [comment]
Unfortunately the error still seems to persist. I upgraded to 0.0.19 and cleared out the local repository and resynced my recipes (500+).

But I just tried a random recipe and only imported one (after clearing out my local repo again) and was actually able to import it. So it seems like one or more recipes deliver the data in the wrong format.

**Comment by ephes** [comment]
Yep, just stumbled over the same recipe, I think 😆. The reason was an unescaped newline in the title of the steps which are joined into the description for Paprika. [Version 0.0.20 ](https://github.com/ephes/kptncook/releases/tag/0.0.20) should fix this.
